import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import { ActionDocketModal } from '../components/Docket/ActionDocketModal';
import { CanonicalCivicState, CivicIntent, ControlledDepartment, UrgencyLevel } from '../types/civic';

describe('ActionDocketModal', () => {
  const mockState: CanonicalCivicState = {
    intent: CivicIntent.WATERLOGGING,
    department: ControlledDepartment.DRAINAGE_STORMWATER,
    location: 'Anna Salai, Chennai',
    landmark: 'Thousand Lights Metro',
    pincode: '600006',
    urgency: UrgencyLevel.HIGH,
    urgency_rationale: 'Flooding blocks active traffic lane during peak monsoon.',
    language: 'en-IN',
    confidence: 0.96,
    description: 'Severe waterlogging at Anna Salai near Thousand Lights metro station.',
  };

  it('contains mandatory wording and ethical disclaimer', () => {
    const handleSubmit = vi.fn();
    const handleClose = vi.fn();

    render(
      <ActionDocketModal
        isOpen={true}
        state={mockState}
        onClose={handleClose}
        onSubmitCase={handleSubmit}
      />
    );

    // Mandatory wording requirement
    expect(
      screen.getByText('Generates an AI-generated Civic Action Docket draft with server-side validation.')
    ).toBeInTheDocument();

    // Ethical transparency disclaimer
    expect(
      screen.getByText('This record is generated by JARVIS Civic and is not proof of official government submission or resolution.')
    ).toBeInTheDocument();

    // Civic record title
    expect(screen.getByText('AI-generated civic grievance record')).toBeInTheDocument();
    expect(screen.getByText('Recommended Department')).toBeInTheDocument();
  });

  it('submits case payload when confirm button is clicked', async () => {
    const handleSubmit = vi.fn().mockResolvedValue(undefined);
    const handleClose = vi.fn();

    render(
      <ActionDocketModal
        isOpen={true}
        state={mockState}
        onClose={handleClose}
        onSubmitCase={handleSubmit}
      />
    );

    const submitBtn = screen.getByRole('button', { name: /Create Civic Action Docket/i });
    fireEvent.click(submitBtn);

    expect(handleSubmit).toHaveBeenCalledTimes(1);
    expect(handleSubmit).toHaveBeenCalledWith(
      expect.objectContaining({
        description: mockState.description,
        location: mockState.location,
        department: ControlledDepartment.DRAINAGE_STORMWATER,
        pincode: '600006',
        is_public: true,
      })
    );
  });
});
