import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import { EvidenceStudio } from '../components/Evidence/EvidenceStudio';
import { evidenceApi } from '../services/api';

vi.mock('../services/api', () => ({
  evidenceApi: {
    uploadEvidence: vi.fn(),
  },
}));

describe('EvidenceStudio', () => {
  it('rejects files larger than 10MB limit', async () => {
    render(<EvidenceStudio initialCaseId="test-case-123" />);

    // Create a 11MB dummy file
    const oversizedFile = new File(['x'.repeat(1024)], 'large-video.mp4', { type: 'video/mp4' });
    Object.defineProperty(oversizedFile, 'size', { value: 11 * 1024 * 1024 });

    const input = document.querySelector('input[type="file"]') as HTMLInputElement;
    expect(input).toBeInTheDocument();

    fireEvent.change(input, { target: { files: [oversizedFile] } });

    await waitFor(() => {
      expect(screen.getByText(/Evidence file exceeds the 10MB limit/i)).toBeInTheDocument();
    });
  });

  it('contains non-government notice', () => {
    render(<EvidenceStudio initialCaseId="test-case-123" />);
    expect(
      screen.getByText(/This record is generated by JARVIS Civic and is not proof of official government submission or resolution/i)
    ).toBeInTheDocument();
  });
});
