import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { TrackingView } from '../components/Tracking/TrackingView';
import { trackingApi, casesApi, auditApi, ApiError } from '../services/api';
import {
  ApplicationRole,
  AuditEvent,
  CaseStatus,
  ControlledDepartment,
  PublicTrackingProjection,
} from '../types/civic';

vi.mock('../services/api', () => {
  class MockApiError extends Error {
    public statusCode?: number;
    constructor(message: string, statusCode?: number) {
      super(message);
      this.name = 'ApiError';
      this.statusCode = statusCode;
    }
  }

  return {
    ApiError: MockApiError,
    trackingApi: {
      getTracking: vi.fn(),
    },
    casesApi: {
      getCase: vi.fn(),
      updateStatus: vi.fn(),
      addResolutionNote: vi.fn(),
      getHistory: vi.fn(),
    },
    auditApi: {
      getCaseAuditTrail: vi.fn(),
    },
  };
});

describe('TrackingView', () => {
  const mockProjection: PublicTrackingProjection = {
    case_id: 'NS-DRA-2026-X9Y2',
    status: 'DOCKET_CREATED',
    recommended_department: 'DRAINAGE_STORMWATER',
    created_at: '2026-09-17T10:00:00Z',
    updated_at: '2026-09-17T10:15:00Z',
  };

  beforeEach(() => {
    vi.clearAllMocks();
    vi.mocked(casesApi.getCase).mockResolvedValue({
      case_id: 'NS-DRA-2026-X9Y2',
      owner_id: 'cit-user-1',
      department: 'DRAINAGE_STORMWATER',
      status: CaseStatus.DOCKET_CREATED,
      description: 'Severe street waterlogging',
      location: 'Anna Salai',
      is_public: true,
      evidence_uris: [],
      resolution_notes: [],
      created_at: '2026-09-17T10:00:00Z',
      updated_at: '2026-09-17T10:15:00Z',
    });
    vi.mocked(casesApi.getHistory).mockResolvedValue([
      {
        milestone_id: 'm1',
        stage: '01_DOCKET_CREATED',
        label: 'Docket Created',
        timestamp: '2026-09-17T10:00:00Z',
        description: 'Civic grievance registered into system',
        notes_count: 0,
      },
    ]);
  });

  it('queries tracking projection and displays safe public details', async () => {
    vi.mocked(trackingApi.getTracking).mockResolvedValueOnce(mockProjection);

    render(<TrackingView />);

    const input = screen.getByPlaceholderText(/Enter Case ID/i);
    const submitBtn = screen.getByRole('button', { name: /Track Docket/i });

    fireEvent.change(input, { target: { value: 'NS-DRA-2026-X9Y2' } });
    fireEvent.click(submitBtn);

    await waitFor(() => {
      expect(screen.getByText('NS-DRA-2026-X9Y2')).toBeInTheDocument();
      expect(screen.getByText('DRAINAGE STORMWATER')).toBeInTheDocument();
      expect(screen.getAllByText('DOCKET CREATED').length).toBeGreaterThanOrEqual(1);
      expect(screen.getAllByText(/Routing Prepared/i).length).toBeGreaterThanOrEqual(1);
      expect(
        screen.getByText(/This record is generated by JARVIS Civic and is not proof of official government submission or resolution/i)
      ).toBeInTheDocument();
    });
  });

  it('handles not-found errors gracefully without crashing', async () => {
    vi.mocked(trackingApi.getTracking).mockRejectedValueOnce(
      new Error('The requested civic record could not be found.')
    );

    render(<TrackingView />);

    const input = screen.getByPlaceholderText(/Enter Case ID/i);
    const submitBtn = screen.getByRole('button', { name: /Track Docket/i });

    fireEvent.change(input, { target: { value: 'invalid-id' } });
    fireEvent.click(submitBtn);

    await waitFor(() => {
      expect(screen.getByText(/Case Lookup Failed/i)).toBeInTheDocument();
      expect(screen.getByText(/The requested civic record could not be found/i)).toBeInTheDocument();
    });
  });

  it('switches to Authority Workflow mode and displays valid next stage transition', async () => {
    vi.mocked(trackingApi.getTracking).mockResolvedValueOnce(mockProjection);

    render(<TrackingView />);

    const input = screen.getByPlaceholderText(/Enter Case ID/i);
    fireEvent.change(input, { target: { value: 'NS-DRA-2026-X9Y2' } });
    fireEvent.click(screen.getByRole('button', { name: /Track Docket/i }));

    await waitFor(() => {
      expect(screen.getByText('NS-DRA-2026-X9Y2')).toBeInTheDocument();
    });

    // Switch to Authority Workflow tab
    const authorityTab = screen.getByRole('tab', { name: /2\. AUTHORITY WORKFLOW/i });
    fireEvent.click(authorityTab);

    // Verify simulation banner & next stage transition panel
    expect(screen.getByText(/SIMULATION \/ TEST MODE/i)).toBeInTheDocument();
    expect(screen.getByText(/CANONICAL LIFECYCLE PROGRESSION/i)).toBeInTheDocument();
    expect(screen.getAllByText(/PREPARE ROUTING/i).length).toBeGreaterThanOrEqual(1);
  });

  it('opens confirmation modal and executes status advance along valid forward path', async () => {
    vi.mocked(trackingApi.getTracking).mockResolvedValueOnce(mockProjection);
    vi.mocked(casesApi.updateStatus).mockResolvedValueOnce({
      case_id: 'NS-DRA-2026-X9Y2',
      owner_id: 'cit-user-1',
      department: 'DRAINAGE_STORMWATER',
      status: CaseStatus.ROUTING_PREPARED,
      description: 'Severe street waterlogging',
      location: 'Anna Salai',
      is_public: true,
      evidence_uris: [],
      resolution_notes: [],
      created_at: '2026-09-17T10:00:00Z',
      updated_at: '2026-09-17T10:20:00Z',
    });

    render(<TrackingView />);

    const input = screen.getByPlaceholderText(/Enter Case ID/i);
    fireEvent.change(input, { target: { value: 'NS-DRA-2026-X9Y2' } });
    fireEvent.click(screen.getByRole('button', { name: /Track Docket/i }));

    await waitFor(() => {
      expect(screen.getByText('NS-DRA-2026-X9Y2')).toBeInTheDocument();
    });

    // Switch to Authority tab
    fireEvent.click(screen.getByRole('tab', { name: /2\. AUTHORITY WORKFLOW/i }));

    // Click advance button
    const advanceBtn = screen.getByRole('button', { name: /PREPARE ROUTING/i });
    fireEvent.click(advanceBtn);

    // Confirmation dialog should appear
    expect(screen.getByText(/Confirm Lifecycle Transition/i)).toBeInTheDocument();

    // Confirm transition
    const confirmBtn = screen.getByRole('button', { name: /CONFIRM & ADVANCE/i });
    fireEvent.click(confirmBtn);

    await waitFor(() => {
      expect(casesApi.updateStatus).toHaveBeenCalledWith(
        'NS-DRA-2026-X9Y2',
        expect.objectContaining({ status: CaseStatus.ROUTING_PREPARED }),
        ApplicationRole.AUTHORITY_OFFICER,
        expect.any(String),
        ControlledDepartment.DRAINAGE_STORMWATER
      );
      expect(screen.getByText(/Case successfully transitioned to ROUTING PREPARED/i)).toBeInTheDocument();
    });
  });

  it('switches to Audit Trail mode and displays restriction state when unauthorized (HTTP 403)', async () => {
    vi.mocked(trackingApi.getTracking).mockResolvedValueOnce(mockProjection);
    vi.mocked(auditApi.getCaseAuditTrail).mockRejectedValueOnce(
      new ApiError('Authorization denied by Cedar policy enforcement.', 403)
    );

    render(<TrackingView />);

    const input = screen.getByPlaceholderText(/Enter Case ID/i);
    fireEvent.change(input, { target: { value: 'NS-DRA-2026-X9Y2' } });
    fireEvent.click(screen.getByRole('button', { name: /Track Docket/i }));

    await waitFor(() => {
      expect(screen.getByText('NS-DRA-2026-X9Y2')).toBeInTheDocument();
    });

    // Switch to Audit tab
    fireEvent.click(screen.getByRole('tab', { name: /3\. AUTHORIZED AUDIT TRAIL/i }));

    await waitFor(() => {
      expect(screen.getByText(/AUDIT TRAIL RESTRICTED/i)).toBeInTheDocument();
      expect(screen.getByText(/AUTHORITY-LEVEL AUTHORIZATION REQUIRED/i)).toBeInTheDocument();
    });
  });

  it('displays authorized audit timeline when permission is granted by Cedar', async () => {
    vi.mocked(trackingApi.getTracking).mockResolvedValueOnce(mockProjection);
    const mockEvents: AuditEvent[] = [
      {
        event_id: 'ev-1',
        case_id: 'NS-DRA-2026-X9Y2',
        event_type: 'DOCKET_CREATED',
        principal_id: 'cit-user-1',
        principal_role: 'CITIZEN',
        outcome: 'SUCCESS',
        previous_status: 'NONE',
        new_status: 'DOCKET_CREATED',
        timestamp: '2026-09-17T10:00:00Z',
      },
      {
        event_id: 'ev-2',
        case_id: 'NS-DRA-2026-X9Y2',
        event_type: 'STATUS_TRANSITION',
        principal_id: 'officer-drainage-1',
        principal_role: 'AUTHORITY_OFFICER',
        principal_department: 'DRAINAGE_STORMWATER',
        outcome: 'SUCCESS',
        previous_status: 'DOCKET_CREATED',
        new_status: 'ROUTING_PREPARED',
        metadata: { note: 'Drainage team inspection scheduled' },
        timestamp: '2026-09-17T10:20:00Z',
      },
    ];
    vi.mocked(auditApi.getCaseAuditTrail).mockResolvedValueOnce(mockEvents);

    render(<TrackingView />);

    const input = screen.getByPlaceholderText(/Enter Case ID/i);
    fireEvent.change(input, { target: { value: 'NS-DRA-2026-X9Y2' } });
    fireEvent.click(screen.getByRole('button', { name: /Track Docket/i }));

    await waitFor(() => {
      expect(screen.getByText('NS-DRA-2026-X9Y2')).toBeInTheDocument();
    });

    // Switch to Audit tab
    fireEvent.click(screen.getByRole('tab', { name: /3\. AUTHORIZED AUDIT TRAIL/i }));

    await waitFor(() => {
      expect(screen.getByText('CEDAR-PROTECTED AUTHORIZED AUDIT TRAIL')).toBeInTheDocument();
      expect(screen.getAllByText('DOCKET_CREATED').length).toBeGreaterThanOrEqual(1);
      expect(screen.getByText('STATUS_TRANSITION')).toBeInTheDocument();
      expect(screen.getByText('Drainage team inspection scheduled')).toBeInTheDocument();
    });
  });
});
