import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import { TrackingView } from '../components/Tracking/TrackingView';
import { trackingApi } from '../services/api';
import { PublicTrackingProjection } from '../types/civic';

vi.mock('../services/api', () => ({
  trackingApi: {
    getTracking: vi.fn(),
  },
}));

describe('TrackingView', () => {
  const mockProjection: PublicTrackingProjection = {
    case_id: 'NS-DRA-2026-X9Y2',
    status: 'TRIAGED',
    recommended_department: 'DRAINAGE_STORMWATER',
    created_at: '2026-09-17T10:00:00Z',
    updated_at: '2026-09-17T10:15:00Z',
  };

  it('queries tracking projection and displays safe public details', async () => {
    vi.mocked(trackingApi.getTracking).mockResolvedValueOnce(mockProjection);

    render(<TrackingView />);

    const input = screen.getByPlaceholderText(/Enter Case ID/i);
    const submitBtn = screen.getByRole('button', { name: /Track Docket/i });

    fireEvent.change(input, { target: { value: 'NS-DRA-2026-X9Y2' } });
    fireEvent.click(submitBtn);

    await waitFor(() => {
      expect(screen.getByText('NS-DRA-2026-X9Y2')).toBeInTheDocument();
      expect(screen.getByText('DRAINAGE STORMWATER')).toBeInTheDocument();
      expect(screen.getByText('TRIAGED')).toBeInTheDocument();
      expect(screen.getAllByText(/Routing Prepared/i).length).toBeGreaterThanOrEqual(1);
      expect(
        screen.getByText(/This record is generated by JARVIS Civic and is not proof of official government submission or resolution/i)
      ).toBeInTheDocument();
    });
  });

  it('handles not-found errors gracefully without crashing', async () => {
    vi.mocked(trackingApi.getTracking).mockRejectedValueOnce(
      new Error('The requested civic record could not be found.')
    );

    render(<TrackingView />);

    const input = screen.getByPlaceholderText(/Enter Case ID/i);
    const submitBtn = screen.getByRole('button', { name: /Track Docket/i });

    fireEvent.change(input, { target: { value: 'invalid-id' } });
    fireEvent.click(submitBtn);

    await waitFor(() => {
      expect(screen.getByText(/Case Lookup Failed/i)).toBeInTheDocument();
      expect(screen.getByText(/The requested civic record could not be found/i)).toBeInTheDocument();
    });
  });
});
